// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXJQfPLlfriOI3_Snz3NHV40hJNRquEaA',
    appId: '1:177852946721:web:9035d4ad9c422fa6280660',
    messagingSenderId: '177852946721',
    projectId: 'kangaroommobileogretmen',
    authDomain: 'kangaroommobileogretmen.firebaseapp.com',
    storageBucket: 'kangaroommobileogretmen.firebasestorage.app',
    measurementId: 'G-JVMBDQ0XEC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoQNoTVpqphkTu18_HhfyGIzoXw6J25nY',
    appId: '1:177852946721:android:60de40e36e24ca41280660',
    messagingSenderId: '177852946721',
    projectId: 'kangaroommobileogretmen',
    storageBucket: 'kangaroommobileogretmen.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeWdjbjYItJLe1ALnbYbTl5e3rrEnFzNk',
    appId: '1:177852946721:ios:95ecd65a77fd1cbc280660',
    messagingSenderId: '177852946721',
    projectId: 'kangaroommobileogretmen',
    storageBucket: 'kangaroommobileogretmen.firebasestorage.app',
    iosBundleId: 'com.example.kangaroomMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDeWdjbjYItJLe1ALnbYbTl5e3rrEnFzNk',
    appId: '1:177852946721:ios:34d59add49ab2802280660',
    messagingSenderId: '177852946721',
    projectId: 'kangaroommobileogretmen',
    storageBucket: 'kangaroommobileogretmen.firebasestorage.app',
    iosBundleId: 'com.missoft.kangarommobileogretmen',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXJQfPLlfriOI3_Snz3NHV40hJNRquEaA',
    appId: '1:177852946721:web:d11c42c3a1a1cd00280660',
    messagingSenderId: '177852946721',
    projectId: 'kangaroommobileogretmen',
    authDomain: 'kangaroommobileogretmen.firebaseapp.com',
    storageBucket: 'kangaroommobileogretmen.firebasestorage.app',
    measurementId: 'G-8J8F253DF6',
  );
}
